# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.create(title: 'A számítógépes ábrázoló geoemtria alapjai ', description: 'Klasszikus ábrázoló geometria,Görbemodellezés,Felületek modellezése.', pages: 485, cover: 'book_covers/12.jpg').authors << [ Author.create(name: 'Klukovits Lajos'),  Author.create(name: 'Móricz Zsigmond') ]
Book.create(title: 'Analízis', description: 'Az analízis történetének rövid áttekintése,A valós számok,Számsorozatok,Egyváltozós függvények,Függvények differenciálása,   Magasabbrendû differenciálhányadosok,Függvénydiszkusszió,Primitív függvény,  Határozott integrál', pages: 228, cover: 'book_covers/18.jpg').authors << Author.create(name: 'Gécseg Ferenc')
Book.create(title: 'Az életbiztosítás alapjai ', description: 'Kamatszámítás, Járadékszámítás, KölcsöntörlesztésA biztosítási díj számításának alapelvei,', pages: 405, cover: 'book_covers/16.jpg').authors << Author.create(name: 'Leindler László')
Book.create(title: 'Bevezetés a differenciálgeometriába ', description: 'Görbék a síkon és a térben,Differenciálható felületek,Differenciálható sokaságok,Riemann-sokaságok.', pages: 285, cover: 'book_covers/10.jpg').authors << Author.create(name: 'Kurusa Árpád')
Book.create(title: 'Bevezetés a lineáris algebrába', description: ' Mátrixok, Az n-edrendû determináns,Inverzmárix,Lineáris egyenletrendszerek,Vektortér, altér, generálás, Lineárisan független és függõ vektorrendszerek,  Véges dimenziós vektorterek,Mátrixok rangja.', pages: 197, cover: 'book_covers/20.jpg').authors << Author.create(name: 'Vármonostory Endre')
Book.create(title: 'Bevezetés a számelméletbe', description: ' Oszthatóság integritástartományokban. Egységek. ,Kongruenciák,Számelméleti függvények,   A tökéletes számok. Barátságos számpárok. Fibonacci- és Lucas-számok ,Primitív gyök,Négyzetes maradékok, Természetes számok felbontása né', pages: 289, cover: 'book_covers/6.jpg').authors << Author.create(name: 'Megyesi László')
Book.create(title: 'Bevezetés a véges dimenziós vektorterek elméletébe', description: ' Halmazok, relációk, leképezések,Valós és komplex számok,Polinomgyûrûk, oszthatóság,A vektorterekkel kapcsolatos alapvetõ fogalmak ,Mátrixok,Véges dimenziós vektortér operátorainak osztályozása, operátorok kanonikus mátrixai,  Euklid', pages: 136, cover: 'book_covers/8.jpg').authors << Author.create(name: 'Kérchy László')
Book.create(title: 'Differenciálegyenletek ', description: 'Lineáris differenciálegyenlet-rendszerek,Nemlineáris differenciálegyenlet-rendszerek,Autonóm rendszerek,Peremérték-feladatok', pages: 428, cover: 'book_covers/5.jpg').authors << Author.create(name: 'Terjéki József')
Book.create(title: 'Differenciálegyenletek numerikus módszerei', description: 'Közönséges differenciálegyenletek kezdetiérték feladata. Analitikus módszerek,Közönséges differenciálegyenletek kezdetiérték feladata. Egylépéses módszerek, Állandó együtthatójú differenciaegyenletek,Közönséges differenciálegyenl', pages: 341, cover: 'book_covers/13.jpg').authors << Author.create(name: 'Hatvani László')
Book.create(title: 'Dinamikus modellek a közgazdaságban ', description: ' I. rész. Differenciálegyenletek és folytonos idejû modellek,II. rész. Differenciaegyenletek és diszkrét idejû modellek', pages: 432, cover: 'book_covers/15.jpg').authors << Author.create(name: 'Bajalinov Erik')
Book.create(title: 'Diszkrét matematika', description: 'Az ítéletkalkulus elemei, Halmazok, leképezések,Relációk, gráfok, Összeszámlálási alapfeladatok,Mûveletek, mûveleti tulajdonságok, Komplex számok, Euklideszi gyûrûk, egyértelmû irreducibilis felbontás,Számelméleti kongruenciák, Pol', pages: 354, cover: 'book_covers/1.jpg').authors << Author.create(name: 'Szendrei Ágnes')
Book.create(title: 'Formális nyelvek és szintaktikus elemzésük', description: 'Fogalmak, jelölések, Generatív nyelvtanok,Reguláris nyelvek,Környezetfüggetlen nyelvek, Az elemzés alapfeladatáról,Felülrõl lefelé haladó elemzési algoritmusok ,Alulról felfelé haladó elemzési algoritmusok', pages: 127, cover: 'book_covers/11.jpg').authors << Author.create(name: 'Fülöp Zoltán')
Book.create(title: 'Halmazelméleti feladatok és tételek', description: '1. Alapmûveletek,  2. Ekvivalencia, 3. A megszámlálható és kontinuum számosság,4. Rendezett halmazok és rendtípusok,5. Rendszámok,6. Számosságok, 7. Végtelen kombinatorika, 8. Kiválasztási axióma,9. Kontinuum hipotézis ,10. Vegyes felada', pages: 461, cover: 'book_covers/7.jpg').authors << Author.create(name: 'Totik Vilmos')
Book.create(title: 'Halmazrendszerek', description: 'Halmazrendszerek, Halmazrendszerek lefogása és páronként diszjunkt részrendszerek keresése, Halmazrendszerek színezése, Halmazrendszerek Vapnyik---Cservonyenkisz-dimenziója,Halmazrendszerek diszkrepanciája,Extremális halmazrendszerek,A halmazr', pages: 357, cover: 'book_covers/19.jpg').authors << Author.create(name: 'Stacho László')
Book.create(title: 'Infor - Matek', description: 'Logikai algebra, Kombinatorikai alapismeretek, A valós számok struktúrája,Halmazok számossága,Boole-algebra, gyûrû, test,Háló , Csoport,Vektoralgebra. Analitikus geometria, Komplex számok,Mátrixalgebra. Determinánsok,   Lineáris egyenletren', pages: 106, cover: 'book_covers/2.jpg').authors << Author.create(name: 'Ablonczy Péter')
Book.create(title: 'Integrálszámítás példatár', description: 'Határozatlan integrál; primitív függvény,Határozott integrál', pages: 399, cover: 'book_covers/9.jpg').authors << Author.create(name: 'Németh József')
Book.create(title: 'Klasszikus és lineáris algebra ', description: 'Halmazelméleti alapok, Véges halmazok permutációi,Az általános algebra elemei,A komplex számok teste Számtest fölötti vektortér,Lineáris egyenletrendszerek,Számtest fölötti polinomok,Polinomok zérushelyeinek kiszámítása,Számtest föl', pages: 151, cover: 'book_covers/14.jpg').authors << Author.create(name: 'Szabó László')
Book.create(title: 'Numerikus módszerek az algebrában és analízisben', description: 'A SAJÁTÉRTÉK FELADAT, MÁTRIXOK ÁLTALÁNOSÍTOTT INVERZE,NEMLINEÁRIS EGYENLETEK ÉS EGYENLETRENDSZEREK MEGOLDÁSA, FÜGGVÉNYEK MINIMALIZÁLÁSA,  FÜGGVÉNYEK KÖZELÍTÉSE , INTEGRÁLOK KÖZELÍTÕ KISZÁMÍTÁSA ', pages: 174, cover: 'book_covers/3.jpg').authors << Author.create(name: 'Móricz Ferenc')
Book.create(title: 'Operációkutatás', description: 'Optimumszámítási modellek és elemeik,Lineáris programozás,Konvex poliéderek és dualitás, Egészértékû programozás, Hiperbolikus programozás,Konvex programozás', pages: 228, cover: 'book_covers/17.jpg').authors << Author.create(name: 'Csákány Béla')
Book.create(title: 'Összeszámlálási problémák ', description: 'Formális hatványsorok, Részhalmazok, Sorbaállítások, permutációk,Halmazok osztályozásai,Egész számok partíciói ,Leképezések összeszámlálása, Racionális generátorfüggvények, lineáris rekurziók, Algebrai generátorfüggvények, polinomiális rekurziók,  Szita módszerek', pages: 450, cover: 'book_covers/4.jpg').authors << Author.create(name: 'Hajnal Péter')
